# Generated by Django 3.0.6 on 2021-02-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCRIO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='meme_url',
            field=models.URLField(max_length=256),
        ),
    ]
