# Generated by Django 3.0.6 on 2021-02-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCRIO', '0004_auto_20210207_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='mid',
            field=models.CharField(max_length=256),
        ),
    ]
