# Generated by Django 3.0.6 on 2021-02-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCRIO', '0008_auto_20210207_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='mcaption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='meme_url',
            new_name='url',
        ),
    ]
