# Generated by Django 3.0.6 on 2021-02-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCRIO', '0009_auto_20210212_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='meme_id',
            new_name='id',
        ),
    ]
