# Generated by Django 3.0.6 on 2021-02-07 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appCRIO', '0003_auto_20210207_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='id',
            field=models.AutoField( primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meme',
            name='mid',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
