# Generated by Django 3.0.6 on 2021-02-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCRIO', '0005_auto_20210207_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='mid',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
