# Generated by Django 3.0.6 on 2021-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCRIO', '0009_auto_20210213_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
